# Generated by Django 3.2.7 on 2021-09-14 07:44

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ToysList',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('name', models.CharField(default='', max_length=150)),
                ('description', models.CharField(default='', max_length=250)),
                ('toy_category', models.CharField(default='', max_length=200)),
                ('release_date', models.DateTimeField(blank=True, help_text='toys release date', null=True)),
            ],
        ),
    ]
